server:
  port: ${wizard.server.port}
  shutdown: graceful
  compression:
    enabled: true

wizard:
  application:
    name: "gaia-x-wizard"
  info:
    name:
    description:
    version:
    contact:
      name:
      email:
      url:
  aws:
    accessKey:
    secretKey:
    hostedZoneId:
    serverIp:
    baseDomain:
    bucket:
    region:
    s3Endpoint:
  database:
    postgres:
      host: localhost
      port: 5432
      name: wizard-master
      username: root
      password: root
      connection-timeout: 120000
      pool-size: 10
      leakDetectionThreshold: 50000
      maxLifetime: 30000
  k8s:
    basePath:
    token:
    serviceName:
    issuer:
  keycloak:
    authServer: http://localhost:8080
    realm: gaia-x
    clientId: gx-sa-wizard
    clientSecret: mEgWQ3GIDsPyZiGhdptotWVyve9WWmVi
    publicClientId: gaia-x-public-client
    apiDocsClient:
    webAuthRedirectUrl:
    actionTokenLifespan: 300
    requiredActionsEmailRedirectionUrl: http://localhost:4000
  security:
    enabled: true
    realm: ${wizard.keycloak.realm}
    clientId: ${wizard.keycloak.client-id}
    auth-server-url: ${wizard.keycloak.auth-server}
    authUrl: ${wizard.security.auth-server-url}/realms/${wizard.security.realm}/protocol/openid-connect/auth
    tokenUrl: ${wizard.security.auth-server-url}/realms/${wizard.security.realm}/protocol/openid-connect/token
    refreshTokenUrl: ${wizard.security.token-url}
    corsOrigins: "http://localhost:4000"
  host:
    signer: http://localhost:8000
    wizard: https://wizard-api.dev.smart-x.smartsenselabs.com/
    messagingQueue: abc
  server:
    port: 8081
  quartz:
    scheduler:
      instanceName: smartSense
      instanceId: AUTO
      batchTriggerAcquisitionMaxCount: 10
      threadPool:
        threadCount: 10
  management:
    port: 8090
  multipart:
    max-file-size: 1MB
    max-request-size: 1MB
  signer-policies:
  vault:
    host: vault.dev.smart-x.smartsenselabs.com
    port: 443
    scheme: https
    authentication: APPROLE
    role-id: ZGRhODRjMjYtMmZjNC1mN2RkLTkwYzktOTAzZmM3ZTc5MzMw
    secret-id: Nzk1NWRlY2MtNTI2Ni1hZDk4LWM1NGQtZmY4OGMzZWJmNTI5
    secret-path: keypair
  gaia-x:
    registryService: https://registry.gaia-x.eu/v1
  context:
    participant:
    registrationNumber:
    tnc:
    serviceOffer:
    ODRLPolicy:
    labelLevel:
  domain:
  gaiax:
    tnc:
  service-endpoint:
    linkDomainType:
    pdpType:
    pdpUrl:
  sslProvider: acme://letsencrypt.org
  tenant:
    liquibase: /migration/tenant/changelog-tenant.xml

spring:
  liquibase:
    change-log: classpath:/migration/master/changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${wizard.application.name}
  #  datasource:
  #    url: jdbc:postgresql://${wizard.database.postgres.host:localhost}:${wizard.database.postgres.port:5432}/${wizard.database.postgres.name:testDB}
  #    username: ${wizard.database.postgres.username:root}
  #    password: ${wizard.database.postgres.password:root}
  #    initialization-mode: never
  #    driverClassName: org.postgresql.Driver
  #    hikari:
  #      connectionTimeout: ${wizard.database.postgres.connection-timeout}
  #      maximumPoolSize: ${wizard.database.postgres.pool-size}
  #      leakDetectionThreshold: 50000
  #      maxLifetime: 30000
  quartz:
    auto-startup: false
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: smartSense
            instanceId: AUTO
            batchTriggerAcquisitionMaxCount: ${wizard.quartz.scheduler.batchTriggerAcquisitionMaxCount}
            batchTriggerAcquisitionFireAheadTimeWindow: 1000
          jobStore:
            isClustered: true
            clusterCheckinInterval: 10000
            acquireTriggersWithinLock: true
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          threadPool:
            threadCount: ${wizard.quartz.scheduler.threadPool.threadCount}
  security:
    oauth2:
      resourceserver:
        jwt:
          #Issuer-uri indicates the iss claims from jwt token
          issuer-uri: ${wizard.security.auth-server-url}/realms/${wizard.security.realm}
          jwk-set-uri: ${wizard.security.auth-server-url}/realms/${wizard.security.realm}/protocol/openid-connect/certs
  cloud:
    vault:
      host: ${wizard.vault.host}
      port: ${wizard.vault.port}
      scheme: ${wizard.vault.scheme}
      authentication: ${wizard.vault.authentication}
      app-role:
        roleId: ${wizard.vault.role-id}
        secretId: ${wizard.vault.secret-id}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        proc:
          param_null_passing: true
        c3p0:
          timeout: 1800
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: ${wizard.multipart.max-file-size}
      max-request-size: ${wizard.multipart.max-request-size}

management:
  server:
    port: ${wizard.management.port}
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*, pre-stop'
  health:
    db:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  swagger-ui:
    oauth:
      clientId: ${wizard.keycloak.api-docs-client}
      clientSecret:
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
  api-docs:
    path: /docs/api-docs
